apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mqtt-binding
spec:
  type: bindings.mqtt
  version: v1
  metadata:
    - name: url
      value: "mqtt://mqtt.hsl.fi:1883"
    - name: consumerID
      value: "{uuid}"
    - name: topic
      value: "$share/{uuid}//hfp/v2/journey/ongoing/vp/bus/#"