apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: car-position-change-events
spec:
  type: bindings.mqtt
  version: v1
  metadata:
    - name: url
      value: "mqtt://mqtt.hsl.fi:1883"
    - name: consumerID
      value: "{uuid}"
    - name: topic
      value: "$share/group-4ca91727-4deb-4b5e-a75b-5986a4261dc3//hfp/v2/journey/ongoing/vp/bus/#"